<?php
namespace eurojet\job\models\_base;

use yii\data\ActiveDataProvider;

/**
 * This is the model base class for the table "job_log".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "JobLog".
 *
 * Columns in table "job_log" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $job_class
 * @property string $start_time
 * @property string $finish_time
 * @property integer $job_status_id
 * @property string $finish_message
 * @property string $create_time
 * @property string $update_time
 * @property string $queue
 * @property integer $progress
 * @property string $job_data
 * @property integer $job_id
 * @property string $token
 * @property string $identifier1
 * @property string $identifier2
 * @property string $identifier3
 * @property string $identifier4
 *
 */
abstract class BaseJobLog extends \yii\db\ActiveRecord {


    public static function tableName() {
        return 'Job_Log';
    }

    public static function label($n = 1) {
        return Yii::t('app', 'JobLog|JobLogs', $n);
    }

    public static function representingColumn() {
        return 'job_class';
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['job_class', 'start_time', 'finish_time', 'job_status_id'], 'required'],
            [['start_time', 'finish_time', 'create_time', 'update_time'], 'safe'],
            [['job_status_id', 'progress', 'job_id'], 'integer'],
            [['finish_message', 'job_data'], 'string'],
            [['job_class', 'identifier1', 'identifier2', 'identifier3', 'identifier4'], 'string', 'max' => 64],
            [['queue'], 'string', 'max' => 45],
            [['token'], 'string', 'max' => 23]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'z_PRIMARY_KEY' => 'ID',
            'job_class' => 'Job Class',
            'start_time' => 'Start Time',
            'finish_time' => 'Finish Time',
            'job_status_id' => 'Job Status',
            'finish_message' => 'Finish Message',
            'create_time' => 'Create Time',
            'update_time' => 'Update Time',
            'queue' => 'Queue',
            'progress' => 'Progress',
            'job_data' => 'Job Data',
            'job_id' => 'Job',
            'token' => 'Token',
            'identifier1' => 'Identifier1',
            'identifier2' => 'Identifier2',
            'identifier3' => 'Identifier3',
            'identifier4' => 'Identifier4',
        ];
    }



    public function relations() {
        return array(
        );
    }

    public function pivotModels() {
        return array(
        );
    }

    public function search($params)
    {
        //alias is needed to support foreign keys of the same model such as $_z_Parent_ID
        $query = self::find();
        $query->select(['`Job_Log`.`z_PRIMARY_KEY`','`Job_Log`.`job_class`','`Job_Log`.`start_time`','`Job_Log`.`finish_time`','`Job_Log`.`job_status_id`','`Job_Log`.`finish_message`','`Job_Log`.`create_time`','`Job_Log`.`update_time`','`Job_Log`.`queue`','`Job_Log`.`progress`','`Job_Log`.`job_data`','`Job_Log`.`job_id`','`Job_Log`.`token`','`Job_Log`.`identifier1`','`Job_Log`.`identifier2`','`Job_Log`.`identifier3`','`Job_Log`.`identifier4`',\common\models\JobLog::labelDef('Job_Log').' label']);

        // add conditions that should always apply here


        // here join with relations name that are needed for sorting/filtering


        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        // add sorting for related fields by public property key


        $this->load($params);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }

        // grid filtering conditions
        $query->andFilterWhere(['like', '`Job_Log`.`z_PRIMARY_KEY`', $this->z_PRIMARY_KEY])
            ->andFilterWhere(['like', '`Job_Log`.`job_class`', $this->job_class])
            ->andFilterWhere(['like', '`Job_Log`.`start_time`', $this->start_time])
            ->andFilterWhere(['like', '`Job_Log`.`finish_time`', $this->finish_time])
            ->andFilterWhere(['like', '`Job_Log`.`job_status_id`', $this->job_status_id])
            ->andFilterWhere(['like', '`Job_Log`.`finish_message`', $this->finish_message])
            ->andFilterWhere(['like', '`Job_Log`.`create_time`', $this->create_time])
            ->andFilterWhere(['like', '`Job_Log`.`update_time`', $this->update_time])
            ->andFilterWhere(['like', '`Job_Log`.`queue`', $this->queue])
            ->andFilterWhere(['like', '`Job_Log`.`progress`', $this->progress])
            ->andFilterWhere(['like', '`Job_Log`.`job_data`', $this->job_data])
            ->andFilterWhere(['like', '`Job_Log`.`job_id`', $this->job_id])
            ->andFilterWhere(['like', '`Job_Log`.`token`', $this->token])
            ->andFilterWhere(['like', '`Job_Log`.`identifier1`', $this->identifier1])
            ->andFilterWhere(['like', '`Job_Log`.`identifier2`', $this->identifier2])
            ->andFilterWhere(['like', '`Job_Log`.`identifier3`', $this->identifier3])
            ->andFilterWhere(['like', '`Job_Log`.`identifier4`', $this->identifier4]);


        return $dataProvider;
    }
}
